// Countries map with Chinese and English names, sorted by English names
export const COUNTRIES_MAP = {
  AM: { name: '亞美尼亞', nameEn: 'Armenia', flag: 'AM_flag', link: 'https://www.facebook.com/WorldSkillsArmenia/', ratio: '2 / 1' },
  AZ: { name: '亞塞拜然', nameEn: 'Azerbaijan', flag: 'AZ_flag', link: 'https://www.instagram.com/worldskillsazerbaijan/', ratio: '2 / 1' },
  BH: { name: '巴林', nameEn: 'Kingdom of Bahrain', flag: 'BH_flag', link: 'https://www.facebook.com/skillsbahrain', ratio: '5 / 3' },
  BD: { name: '孟加拉', nameEn: 'Bangladesh', flag: 'BD_flag', link: 'https://www.skillsportal.gov.bd/#/', ratio: '5 / 3' },
  BT: { name: '不丹', nameEn: 'Bhutan', flag: 'BT_flag', link: 'https://education.gov.bt/' },
  BN: { name: '汶萊', nameEn: 'Brunei Darussalam', flag: 'BN_flag', link: 'https://ibte.edu.bn/', ratio: '2 / 1' },
  TW: { name: '中華台北', nameEn: 'Chinese Taipei', flag: 'TW_flag', link: 'https://reurl.cc/ekV0nR', ratio: '6250 / 4167' },
  IN: { name: '印度', nameEn: 'India', flag: 'IN_flag', link: 'https://nsdcindia.org/' },
  ID: { name: '印尼', nameEn: 'Indonesia', flag: 'ID_flag', link: 'https://www.instagram.com/puspresnas/' },
  IR: { name: '伊朗', nameEn: 'Iran', flag: 'IR_flag', link: 'https://www.facebook.com/WorldSkillsIran/', ratio: '7 / 4' },
  JP: { name: '日本', nameEn: 'Japan', flag: 'JP_flag', link: 'https://worldskills.jp/en/' },
  JO: { name: '約旦', nameEn: 'Hashemite Kingdom of Jordan', flag: 'JO_flag', link: 'https://reurl.cc/5R3GVR', ratio: '2 / 1' },
  KR: { name: '韓國', nameEn: 'Korea', flag: 'KR_flag', link: 'https://meister.hrdkorea.or.kr/eng/main.do' },
  KW: { name: '科威特', nameEn: 'Kuwait', flag: 'KW_flag', link: 'https://www.paaet.edu.kw/en/main/vision-and-mission/', ratio: '2 / 1' },
  KG: { name: '吉爾吉斯', nameEn: 'Kyrgyzstan', flag: 'KG_flag', link: 'https://www.instagram.com/worldskillskyrgyzstan', ratio: '5 / 3' },
  MY: { name: '馬來西亞', nameEn: 'Malaysia', flag: 'MY_flag', link: 'https://www.skillsmalaysia.gov.my/ms/', ratio: '2 / 1' },
  MV: { name: '馬爾地夫', nameEn: 'Maldives', flag: 'MV_flag', link: 'https://www.mnsda.gov.mv/' },
  MN: { name: '蒙古', nameEn: 'Mongolia', flag: 'MN_flag', link: 'https://www.facebook.com/VETPartnership/about', ratio: '2 / 1' },
  OM: { name: '阿曼', nameEn: 'Oman', flag: 'OM_flag', link: 'https://www.instagram.com/oman_skills/?hl=en', ratio: '2 / 1' },
  PS: { name: '巴勒斯坦', nameEn: 'Palestine', flag: 'PS_flag', link: 'https://www.facebook.com/Palestineskills/', ratio: '2 / 1' },
  PG: { name: '巴布亞新幾內亞', nameEn: 'Papua New Guinea', flag: 'PG_flag', link: 'https://web.dherst.gov.pg/', ratio: '4 / 3' },
  PH: { name: '菲律賓', nameEn: 'Philippines', flag: 'PH_flag', link: 'https://www.facebook.com/worldskillsphofficial/', ratio: '2 / 1' },
  SA: { name: '沙烏地阿拉伯', nameEn: 'Saudi Arabia', flag: 'SA_flag', link: 'https://tvtc.gov.sa/En/Pages/default.aspx' },
  LK: { name: '斯里蘭卡', nameEn: 'Sri Lanka', flag: 'LK_flag', link: 'https://course.vta.lk/', ratio: '2 / 1' },
  TH: { name: '泰國', nameEn: 'Thailand', flag: 'TH_flag', link: 'https://www.facebook.com/worldskillsthailand/' },
  TL: { name: '東帝汶', nameEn: 'Timor-Leste', flag: 'TL_flag', link: 'https://indmo.gov.tl/east-timor-promotional-skills/', ratio: '2 / 1' },
  AE: { name: '阿拉伯聯合大公國', nameEn: 'United Arab Emirates', flag: 'AE_flag', link: 'https://www.emiratesskills.ae/en/Pages/default.aspx', ratio: '2 / 1' },
  UZ: { name: '烏茲別克斯坦', nameEn: 'Uzbekistan', flag: 'UZ_flag', link: 'https://worldskills.uz/en', ratio: '2 / 1' },
  YE: { name: '葉門', nameEn: 'Yemen', flag: 'YE_flag', link: 'https://reurl.cc/2Qam46' },
}

// All participating countries sorted by English names (31 countries total)
export const PARTICIPATING_COUNTRIES = [
  { code: 'AU', name: '澳洲', nameEn: 'Australia', flag: 'AU_flag', link: 'https://www.worldskills.org.au/', ratio: '2 / 1' },
  { code: 'AZ', name: '亞塞拜然', nameEn: 'Azerbaijan', flag: 'AZ_flag', link: 'https://www.instagram.com/worldskillsazerbaijan/', ratio: '2 / 1' },
  { code: 'BN', name: '汶萊', nameEn: 'Brunei Darussalam', flag: 'BN_flag', link: 'https://ibte.edu.bn/', ratio: '2 / 1' },
  { code: 'TW', name: '中華台北', nameEn: 'Chinese Taipei', flag: 'TW_flag', link: 'https://reurl.cc/ekV0nR', ratio: '6250 / 4167' },
  { code: 'DE', name: '德國', nameEn: 'Germany', flag: 'DE_flag', link: 'https://worldskillsgermany.com/', ratio: '5 / 3' },
  { code: 'HU', name: '匈牙利', nameEn: 'Hungary', flag: 'HU_flag', link: 'https://mkik.hu/kepzes-oktatas', ratio: '2 / 1' },
  { code: 'IN', name: '印度', nameEn: 'India', flag: 'IN_flag', link: 'https://nsdcindia.org/' },
  { code: 'ID', name: '印尼', nameEn: 'Indonesia', flag: 'ID_flag', link: 'https://www.instagram.com/puspresnas/' },
  { code: 'IR', name: '伊朗', nameEn: 'Iran', flag: 'IR_flag', link: 'https://www.facebook.com/WorldSkillsIran/', ratio: '7 / 4' },
  { code: 'JP', name: '日本', nameEn: 'Japan', flag: 'JP_flag', link: 'https://worldskills.jp/en/' },
  { code: 'JO', name: '約旦', nameEn: 'Hashemite Kingdom of Jordan', flag: 'JO_flag', link: 'https://reurl.cc/5R3GVR', ratio: '2 / 1' },
  { code: 'KR', name: '韓國', nameEn: 'Korea', flag: 'KR_flag', link: 'https://meister.hrdkorea.or.kr/eng/main.do' },
  { code: 'KW', name: '科威特', nameEn: 'Kuwait', flag: 'KW_flag', link: 'https://www.paaet.edu.kw/en/main/vision-and-mission/', ratio: '2 / 1' },
  { code: 'KG', name: '吉爾吉斯', nameEn: 'Kyrgyzstan', flag: 'KG_flag', link: 'https://www.instagram.com/worldskillskyrgyzstan', ratio: '5 / 3' },
  { code: 'LI', name: '列支敦斯登', nameEn: 'Principality of Liechtenstein', flag: 'LI_flag', link: 'https://www.worldskills.li/', ratio: '5 / 3' },
  { code: 'MY', name: '馬來西亞', nameEn: 'Malaysia', flag: 'MY_flag', link: 'https://www.skillsmalaysia.gov.my/ms/', ratio: '2 / 1' },
  { code: 'MN', name: '蒙古', nameEn: 'Mongolia', flag: 'MN_flag', link: 'https://www.facebook.com/VETPartnership/about', ratio: '2 / 1' },
  { code: 'NL', name: '荷蘭', nameEn: 'Netherlands', flag: 'NL_flag', link: 'https://worldskillsnetherlands.nl/teamnl/' },
  { code: 'OM', name: '阿曼', nameEn: 'Oman', flag: 'OM_flag', link: 'https://www.instagram.com/oman_skills/?hl=en', ratio: '2 / 1' },
  { code: 'PS', name: '巴勒斯坦', nameEn: 'Palestine', flag: 'PS_flag', link: 'https://www.facebook.com/Palestineskills/', ratio: '2 / 1' },
  { code: 'PH', name: '菲律賓', nameEn: 'Philippines', flag: 'PH_flag', link: 'https://www.facebook.com/worldskillsphofficial/', ratio: '2 / 1' },
  { code: 'QA', name: '卡達', nameEn: 'Qatar', flag: 'QA_flag', link: 'https://www.edu.gov.qa/en/News/Details/8812800', ratio: '25 / 6' },
  { code: 'RO', name: '羅馬尼亞', nameEn: 'Romania', flag: 'RO_flag', link: 'https://www.worldskills.ro/' },
  { code: 'SA', name: '沙烏地阿拉伯', nameEn: 'Saudi Arabia', flag: 'SA_flag', link: 'https://tvtc.gov.sa/En/Pages/default.aspx' },
  { code: 'SE', name: '瑞典', nameEn: 'Sweden', flag: 'SE_flag', link: 'https://www.worldskills.se/', ratio: '8 / 5' },
  { code: 'CH', name: '瑞士', nameEn: 'Switzerland', flag: 'CH_flag', link: 'https://swiss-skills.ch/de', ratio: '1 / 1' },
  { code: 'TH', name: '泰國', nameEn: 'Thailand', flag: 'TH_flag', link: 'https://www.facebook.com/worldskillsthailand/' },
  { code: 'TL', name: '東帝汶', nameEn: 'Timor-Leste', flag: 'TL_flag', link: 'https://indmo.gov.tl/east-timor-promotional-skills/', ratio: '2 / 1' },
  { code: 'AE', name: '阿拉伯聯合大公國', nameEn: 'United Arab Emirates', flag: 'AE_flag', link: 'https://www.emiratesskills.ae/en/Pages/default.aspx', ratio: '2 / 1' },
  { code: 'UK', name: '英國', nameEn: 'United Kingdom', flag: 'UK_flag', link: 'https://www.worldskillsuk.org/', ratio: '2 / 1' },
  { code: 'UZ', name: '烏茲別克斯坦', nameEn: 'Uzbekistan', flag: 'UZ_flag', link: 'https://worldskills.uz/en', ratio: '2 / 1' },
  { code: 'VN', name: '越南', nameEn: 'Vietnam', flag: 'VN_flag', link: 'https://english.molisa.gov.vn/topic/242157' },
]
