name: Deploy Develop

on:
  push:
    branches: [develop/**]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Cloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          tags: |
            ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.CLOUD_RUN_SERVICE }}
      - name: 'Deploy to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          image: '${{ secrets.ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.CLOUD_RUN_SERVICE }}:latest'
          region: ${{ secrets.REGION }}
